# Generated by Django 4.2.18 on 2025-03-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pqty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
